version: '3.4'

services:
  makeitsimple.webapi:
    image: ${DOCKER_REGISTRY-}makeitsimplewebapi
    build:
      context: .
      dockerfile: MakeItSimple.WebApi/Dockerfile
    ports:
            - "5000:5000"
            - "5001:5001"

  mis.database: 
     image: mcr.microsoft.com/mssql/server:2022-latest
     container_name: mis.database
     environment:
         - ACCEPT_EULA=Y
         - MSSQL_SA_PASSWORD=philip13
         - DB_NAME=misdb
         - DB_SA_PASSWORD=philip13 
     volumes:
        - ./.containers/rdf-arcana-db:/var/lib/sqlserver/data
     ports:
        - "4232:4232"