version: '3.4'
networks: 
  makeitsimple.webapi:
    
services:
  makeitsimple.webapi:
    image: ${DOCKER_REGISTRY-}makeitsimplewebapi
    build:
      context: .
      dockerfile: MakeItSimple.WebApi/Dockerfile
    ports:
            - "5000:5000"
            - "5001:5001"
    depends_on: 
      - mis.database
    networks: 
      - makeitsimple.webapi

  mis.database: 
     image: mysql:8.3.0
     container_name: mis.database
     environment:
         - MYSQL_ROOT_PASSWORD=test
         - DB_HOST=mis
         - DB_NAME=misdb
     networks:
       - makeitsimple.webapi
     volumes:
        - ./.containers/rdf-arcana-db:/var/lib/mysql/data
     ports:
        - "8003:3306"